Microverse tribute page review
usorfaitheloho/Microverse-tribute-page-review pull request #1
Opened 2022-01-17 22:00 UTC by usorfaitheloho

### Tribute page i made during the microverse trials

2022-01-17 22:30 UTC, usorfaitheloho reviewed
### ♻️ Required changes

- Add a more descriptive readme to make your project look more professional 

- Add linters to your project to give you a proper code structuring guide to make your codes more maintainable as it grows larger.

Look at the other suggestions below for ,more information about the required changes you are to make.

Happy coding 👏

2022-01-17 22:30 UTC, usorfaitheloho commented on index.html
> +      <!--  <li><strong>1914</strong> - Born in Cresco, Iowa</li> -->
please remove unnecessary comments from your code to make it more readable and easy to maintain

2022-01-17 22:30 UTC, usorfaitheloho commented on index.html
> +        <li>1939<strong></strong>- Has to stop school and save up more money. Works in the Civilian
this line of the code looks incorrect, I think you were trying to use the `<strong>` tags within the year value.

2022-01-17 22:30 UTC, usorfaitheloho commented on style.css
> + }
I suggest you use style linters to give you an orderliness when writing your CSS codes, so your codes look cleaner and easy to maintain 😉

2022-01-17 22:30 UTC, usorfaitheloho commented on index.html
> +
Please remove unnecessary whitespace to make your code look clean

2022-01-17 23:30 UTC, ShinobiWarior requested changes
## Hi @usorfaitheloho 👋🏼 , 

### STATUS: Changes required! ♻️♻️♻️

You did a great job so far. You showed that you know how to use GitHub features for reviews!
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://c.tenor.com/26f7XoUC1AIAAAAd/so-close-jim-halpert.gif)
.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-17 23:30 UTC, ShinobiWarior commented on index.html
> +        <li>1939<strong></strong>- Has to stop school and save up more money. Works in the Civilian
[Requred]
- [ ] Remember to be polite and clear in your comments - your job here is to help another person improve in a friendly way.
Instead of just declaring what mistake you find try to express it in a more friendly manner. For example in this case I think it would be sound better if you write something like this:
"I believe that you made a error on line 38. You probably want to move year into `<strong>` tags. Please make sure that you don't have unused tags in your code. That way your code will look much cleaner."

2022-01-17 23:30 UTC, ShinobiWarior commented on style.css
> + }
This is the great comment. Try to make others to be more like this one. 🔝

2022-01-18 08:33 UTC, elmar8287 approved these changes
Hi @usorfaitheloho , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉🎉🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-19 11:41 UTC, merged